<?php

namespace Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-03 at 19:22:27.
 */
class ClientTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Client
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Client;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers Core\Client::authenticate
   * @todo   Implement testAuthenticate().
   */
  public function testAuthenticate() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::get
   * @todo   Implement testGet().
   */
  public function testGet() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::post
   * @todo   Implement testPost().
   */
  public function testPost() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::getHttpClient
   * @todo   Implement testGetHttpClient().
   */
  public function testGetHttpClient() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::setHttpClient
   * @todo   Implement testSetHttpClient().
   */
  public function testSetHttpClient() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::api
   * @todo   Implement testApi().
   */
  public function testApi() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::getRateLimit
   * @todo   Implement testGetRateLimit().
   */
  public function testGetRateLimit() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::clearHeaders
   * @todo   Implement testClearHeaders().
   */
  public function testClearHeaders() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Core\Client::setHeaders
   * @todo   Implement testSetHeaders().
   */
  public function testSetHeaders() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
