<?php

namespace Core\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-03 at 19:22:27.
 */
class ApiLimitExceedExceptionTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var ApiLimitExceedException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new ApiLimitExceedException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}
